language: node_js
sudo: false
node_js:
  - 6.4

before_install:
  - npm i nsp -g

after_script:
  - nsp audit-package
  - npm run coverage

notifications:
  webhooks:
    urls:
      secure: "GpBVjayfjww/P3ELW9qoCcoAipefTWNi1HUibfOZw7SOTtQt6mNq6dTwmPkW7Zc5RuWd+SfJjDopBY/L+cebg6s85cl9TeTPsbzB+fuZXLr8QkUFWWKzpPKGRx2YPK2XHkMch88osikhGoP0gaz/7fw/j9AvcSwnjZACKsGMmQD8Xg20zFWuG/RPUsMebMNPeLPLKtQ+LTdmgy8L8SoxDJHMDAa5dTnKpP6HK1OjkH7Se8Ym2+n5q35pQUYg/eYXjQeScLWwTyGqBEaxUmrL6io9mXzkEzhn4loawXI+QYF1+DRLMBKThcNYBLZxm4/cVru7orINupjID+EJG8mB1fi9ffl1BcK3yUJGEZSPB/r8OwlxlkWbuxxVn/APGoc0xYCubll5M1lqeq3IyBjW80NXsBsVV9+EZ8C/nSl/Ej784B26XnIXwMiRayIsXlMll55VFLhoWkiBg/CKh3Y6uPP2U14OC4QWZixpX44IDNnLv3D7KLYsX+piszhxxIXEsnnDF6eq4D9tc+9FWbmi/mcKooCUi+AvaJVsJfywSY5ARWp2v91ruFiAOhLgna4ZuX2XPMREwGWF0ZSma3d5WDlp+1zr3yfEn79g2vD7/vsKewnKddCFk/VrvQaTDPdK4NrNzXdRxk7Pg9/r6D1c9jlRhwS/J7Rczg3FD6Qkwmg="
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
